//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int MedicineID { get; set; }
        public string MedicineBarCode { get; set; }
        public string MedicineName { get; set; }
        public int MedicinePrice { get; set; }
        public int MedicineMg { get; set; }
    }
}
